### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'table.csv'

### ISSUE THREAD

**Issue by PaulineJac** [PonteIneptique/choco-mufin#10]
Hello, 

During the last update of my corpus (modification of some codes for segmOnto), Github Actions shows me this error when running Choco-Mufin : 
```
Run chocomufin generate table.csv ./Grountruth/Data/*.xml
[7](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:7)
Traceback (most recent call last):
[8](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:8)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/bin/chocomufin", line 8, in <module>
[9](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:9)
    sys.exit(cli.main())
[10](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:10)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line [11](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:11)30, in __call__
11
    return self.main(*args, **kwargs)
[12](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:12)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1055, in main
[13](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:13)
    rv = self.invoke(ctx)
[14](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:14)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
[15](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:15)
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[16](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:16)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
[17](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:17)
    return ctx.invoke(self.callback, **ctx.params)
[18](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:18)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/core.py", line 760, in invoke
[19](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:19)
    return __callback(*args, **kwargs)
[20](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:20)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
[21](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:21)
    return f(get_current_context(), *args, **kwargs)
[22](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:22)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/chocomufin/cli.py", line 148, in generate
[23](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:23)
    update_table(
[24](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:24)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/chocomufin/funcs.py", line 465, in update_table
[25](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:25)
    prior = {row["char"]: row for row in (Translator.get_csv(table_file))}
[26](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:26)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/chocomufin/funcs.py", line 465, in <dictcomp>
[27](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:27)
    prior = {row["char"]: row for row in (Translator.get_csv(table_file))}
[28](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:28)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/chocomufin/funcs.py", line 310, in get_csv
[29](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:29)
    with open(table_file) as f:
[30](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:30)
FileNotFoundError: [Errno 2] No such file or directory: 'table.csv'
[31](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/runs/6002333610?check_suite_focus=true#step:5:31)
Error: Process completed with exit code 1.
```

My script is available [here](https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/blob/main/.github/workflows/htr-united-workflows.yml). 

Would you know how to fix this error? 
Thanks a lot for your help, 
Pauline Jacsont

**Comment by PonteIneptique** [comment]
I am sorry for the delay, I'll have a look at it on monday !

**Comment by PonteIneptique** [comment]
Can you rerun your tests (you can do this manually here: https://github.com/DesenrollandoElCordel/FoNDUE-Spanish-chapbooks-Dataset/actions/runs/2182785978 ) and tell me if the bug is still here ?

**Comment by PaulineJac** [comment]
Hello, 
Thank you for your answers. I have manually restarted my tests and the error is still there : 
```
File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/chocomufin/funcs.py", line 310, in get_csv
with open(table_file) as f: 
FileNotFoundError: [Errno 2] No such file or directory: 'table.csv'
Error: Process completed with exit code 1.
```
Thank you for your help.

**Comment by PonteIneptique** [comment]
I am completely puzzled by this issue, as I am unable to replicate it locally. But I se that nothing wrong is going on in the setup phase, so it's not an issue like that either...
I'll keep investigating.

**Comment by PonteIneptique** [comment]
OK, I found the bug, I'll release a fix tomorrow.

For tomorrow me, on line https://github.com/PonteIneptique/choco-mufin/blob/29b6132048ed7c73cce6d2044f58327332c98816/chocomufin/funcs.py#L464 , I don't check if the file exist. Local test might have not revealed the issue because a table.csv file existed locally.

**Comment by PaulineJac** [comment]
Thank you very much for the investigation, I will restart the test today as soon as you have modified the line concerned.

**Comment by PonteIneptique** [comment]
This should be fix, wait at least 5 minutes before restarting the test ;)

**Comment by PaulineJac** [comment]
Thank you very much! 
Everything works perfectly now 🥳
